# Generated by Django 3.2.5 on 2023-10-08 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('TAMIL', 'TAMIL'), ('ENGLISH', 'ENG'), ('MATHS', 'MATH'), ('PHYSICE', 'PHY'), ('CHEMISTRY ', 'CHEMISTRY'), ('COMPUTER SCIENCE', 'CS')], default='', max_length=50)),
                ('exp', models.IntegerField()),
                ('hod', models.BooleanField()),
                ('phone', models.IntegerField()),
                ('slug', models.SlugField(unique=True)),
                ('cls_incharge', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('dept', models.CharField(choices=[('B.E - COMPUTER SCIENCE AND ENGINEERING', 'B.E-CSE'), ('B.E-CIVIL ENGINEERING', 'B.E CIVIL'), ('B.E - ELECTRONICS AND COMMUNICATION ENGINEERING', 'B.E-ECE'), ('B.E - ELECTRICAL AND ELECTRONICS ENGINEERING', 'B.E-EEE'), ('B.TECH -ENGINEERING IN INFORMATION TECHNOLOGY ', 'B.TECH-IT'), ('B.E - MECHANICAL', 'B.E -MECH')], default='B.E - COMPUTER SCIENCE AND ENGINEERING', max_length=50)),
                ('year', models.IntegerField()),
                ('div', models.CharField(max_length=10)),
                ('rollno', models.CharField(max_length=10)),
                ('phone', models.BigIntegerField()),
                ('address', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('subject', models.JSONField()),
                ('e_result', models.BooleanField()),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
