# Generated by Django 3.2.5 on 2023-10-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='name',
        ),
        migrations.RemoveField(
            model_name='result',
            name='slug',
        ),
    ]
